language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.8

# command to install dependencies
install:
  - wget http://sphinxsearch.com/files/sphinxsearch_2.3.1-beta-0ubuntu12~trusty_amd64.deb -qO /tmp/sphinxsearch-beta.deb
  - sudo dpkg -i /tmp/sphinxsearch-beta.deb
  - pip install Django==$DJANGO
  - pip install -r test-requires.txt

# command to run tests
script:
    - searchd -c `pwd`/test_config/sphinx.conf
    - python ./manage.py test

after-script: kill `cat /tmp/searchd.pid`
