language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=2.0

# command to install dependencies
install:
  - sudo add-apt-repository ppa:builds/sphinxsearch-rel22 -y
  - sudo apt-get update
  - sudo apt-get install -y sphinxsearch
  - pip install Django==$DJANGO
  - pip install -r test-requires.txt
  - pip install codecov

# command to run tests
script:
    - searchd -c `pwd`/test_config/sphinx.conf
    - python -m coverage run ./manage.py test -v3

after-script: kill `cat /tmp/searchd.pid`
after_success: codecov
