language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.8
  - DJANGO=1.9

matrix:
  exclude:
  - python: "3.3"
    env: DJANGO=1.9

# command to install dependencies
install:
  - pip install Django==$DJANGO
  - pip install -r test-requires.txt

# command to run tests
script:
    - searchd -c `pwd`/test_config/sphinx.conf
    - python ./manage.py test -v3

after-script: kill `cat /tmp/searchd.pid`
