version: "3.5"
services:
    sphinxsearch:
        image: macbre/sphinxsearch:3.1.1
        container_name: sphinxsearch
        ports:
            - "9307:9307"
        volumes:
            - "./test_config/:/opt/sphinx/conf/"
            - "/tmp/:/sphinxdata/indexes/"